### ISSUE TITLE
in azure view, the child nodes under a database node are wrong

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio-mysql#79] opened 2022-10-06 16:52 UTC
![image](https://user-images.githubusercontent.com/13777222/194372770-8bc4ac78-7bce-48af-84e7-12cfbde851bc.png)

looks like the same as the child nodes of a server node

**Comment by rishky-msft** [comment] 2022-10-10 12:04
@alanrenmsft 

I checked the behaviour. In Azure tab, on expanding the databases, ads is sending new connection request.
This is not the behaviour in Servers tab.

Created an issue in azuredatastudio repo.
https://github.com/microsoft/azuredatastudio/issues/20789

Can you please check this?

**Comment by alanrenmsft** [comment] 2022-10-13 03:16
@rishky-msft the issue in azure data studio has been fixed, please fix the issue in the extension that you cannot connect to a database directly.

**Comment by rishky-msft** [comment] 2022-10-13 03:27
@alanrenmsft 

There is always server level connection being made in the mysql.
And only those databases will be shown to user whose permissions user have.

So showing server level nodes is expected behavior for MySQL.

Closing this thread as the issue is fixed at ADS end.

**Closed by rishky-msft** 2022-10-13 03:27 UTC

**Comment by alanrenmsft** [comment] 2022-10-13 16:01
@rishky-msft but if that is the case, why is the database selector needed for mysql in the connection dialog?
