### ISSUE TITLE
Incompatible version Azure Data Studio > Minimal Requirement Azure Data Studio?

### ISSUE THREAD

**Issue by jordi00113** [microsoft/azuredatastudio-mysql#77] opened 2022-10-05 18:33 UTC
Azuredatastudio MySQL not compatible with Azure Data Studio 1.34.0 
Is it somewhere mentioned what the minimal requirement version for Azure Data Studio is?

![image](https://user-images.githubusercontent.com/37302148/194135411-445e3e58-1a12-4657-a422-00b38a39697c.png)

**Comment by jordi00113** [comment] 2022-10-05 18:39
Updated to latest Azure Data Studio (1.39.1)
With this version, it clearly shows the minimal version of Azure Data Studio
![image](https://user-images.githubusercontent.com/37302148/194136968-1f58f520-ca04-4c36-a030-9ed0a17e883e.png)

**Comment by alanrenmsft** [comment] 2022-10-05 21:06
@chris-larsen @jordi00113 once you are using the insider build, you should be able to see the mysql extension in the extension list and install directly., you don't have to download it manually.

**Comment by alanrenmsft** [comment] 2022-10-06 03:40
I guess we should close this issue since it is by design at the moment.

**Closed by alanrenmsft** 2022-10-06 03:40 UTC
